#!/usr/bin/env bash

#-------------------------- Helper functions --------------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[42m'
yellow='\033[1;33m'
NC='\033[0m'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

#--------------------------- Execution --------------------------------------

fin exec backstop reference --config='backstop.config.js' $1
echo -e "Reference samples taken. After making HTML/CSS changes, please run ${yellow}fin backstop/test${NC} to view differences."