#!/usr/bin/env bash

if [ "$1" == "watch" ]; then
  fin exec npm run watch
elif [ "$1" == "compile" ]; then
  if [ "$2" == "--force" ]; then
    fin exec npm run compile:force
  else
    fin exec npm run compile
  fi
else
  echo "***********************************************"
  echo " Valid options for sass are 'watch', 'compile' ";
  echo "***********************************************"
fi