version: "2.1"
services:
  # MailHog
  # http://mail.<VIRTUAL_HOST>
  mail:
    extends:
      file: ${HOME}/.docksal/stacks/services.yml
      service: mail
  cli:
    image: ${COMPOSE_PROJECT_NAME_SAFE}_cli
    build: services/cli
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
      - COMPOSER_PROCESS_TIMEOUT=20000
  # PHPMyAdmin http://pma.<VIRTUAL_HOST>
  pma:
    hostname: pma
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    labels:
      - io.docksal.virtual-host=pma.${VIRTUAL_HOST}