#!/usr/bin/env bash

## Opens txt file
##
## Usage: fin dbcreds

# Abort if anything fails
set -e

container_port=$(docker ps --all --filter 'label=com.docker.compose.service=db' --filter "label=com.docker.compose.project=${COMPOSE_PROJECT_NAME_SAFE}" --format '{{.Ports}}' | sed 's/.*0.0.0.0://g'|sed 's/->.*//g')
HOST=${VIRTUAL_HOST}
DB=${MYSQL_DATABASE:-default}
USER=${MYSQL_USER:-user}
PASS=${MYSQL_PASSWORD:-user}
NAME=${COMPOSE_PROJECT_NAME}

PORT=${PORT:-$container_port}

FILENAME=/tmp/docksal-sequelpro-${RANDOM}.html
cat <<EOT >> $FILENAME
<html>
<head>
<style>
table td { padding:8px;border:1px solid #ccc; }
table td:first-child { background: #ebebeb; }
</style>
</head>
<body>
<h1>Drupal local database credentials</h1>
<table>
<tr>
      <td><strong>database: </strong></td>
      <td>${DB}</td>
</tr>
<tr>
      <td><strong>host: </strong></td>
      <td>${HOST}</td>
</tr>
<tr>
      <td><strong>name: </strong></td>
      <td>${NAME}</td>
</tr>
<tr>
      <td><strong>user: </strong></td>
      <td>${USER}</td>
</tr>
<tr>
      <td><strong>password: </strong></td>
      <td>${PASSWORD}</td>
</tr>
<tr>
      <td><strong>port: </strong></td>
      <td>${PORT}</td>
</tr>
</table>
</body>
</html>
EOT

open $FILENAME
